name: Pull Request Test Suite

on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with gradle
        run: ./gradlew --info test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml

      # - name: Cleanup Gradle Cache
      #   if: ${{ always() }}
      #   run: |
      #     rm -f ~/.gradle/caches/modules-2/modules-2.lock
      #     rm -f ~/.gradle/caches/modules-2/gc.properties
        